EXEC sp_rename 'dbo.[PURCHASE_INVOICE].PURCHASEINVOICEID', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.[PURCHASE_INVOICE].VOUCHER_NO', 'VOUCHERNO', 'COLUMN';
EXEC sp_rename 'dbo.[PURCHASE_INVOICE].PURCHASEINVOICE_DATE', 'DATE', 'COLUMN';
EXEC sp_rename 'dbo.[PURCHASE_INVOICE].GROSS_AMOUNT', 'GROSSAMOUNT', 'COLUMN';
EXEC sp_rename 'dbo.[PURCHASE_INVOICE].NET_AMOUNT', 'NETAMOUNT', 'COLUMN';
EXEC sp_rename 'dbo.[PURCHASE_INVOICE].TOTAL_AMOUNT', 'TOTALAMOUNT', 'COLUMN';
 
ALTER TABLE [dbo].[PURCHASE_INVOICE_DETAILS] DROP CONSTRAINT [DF__tblPurcha__TaxID__1328BA3B]
GO

ALTER TABLE [PURCHASE_INVOICE_DETAILS]
ALTER COLUMN TAXID int NULL;
GO

ALTER TABLE PURCHASE_INVOICE ADD ENTITYNAME NVARCHAR(100);
GO

ALTER PROCEDURE [dbo].[SP_GET_PURCHASE_INVOICE]
@ID INT = 0
AS
BEGIN

	SELECT * FROM PURCHASE_INVOICE WHERE ID = CASE WHEN @ID > 0 THEN @ID ELSE ID END;
	IF(@ID > 0)
	BEGIN

		SELECT SD.*, P.CODE PRODUCTCODE, SD.PURCHASEINVOICE_DETAILID ID, SD.PURCHASEINVOICEID MASTERID, SD.PURCHASERATE PRICE, 
		P.ENGNAME PRODUCTNAME, DISCPERCENTAGE DISCPERCENT, SD.NET_AMOUNT NETAMOUNT, 
		P.UNITID DEFAULTUNITID, U.[NAME] DEFAULTUNITNAME, U.SYMBOL DEFAULTUNITSYMBOL FROM PURCHASE_INVOICE_DETAILS SD 
		INNER JOIN PRODUCT P ON SD.PRODUCTID = P.ID 
		INNER JOIN UNIT U ON SD.QTYUNITID = U.ID  WHERE PURCHASEINVOICEID = @ID

	END
END
GO


ALTER PROC [dbo].[SP_PURCHASE_INVOICE_DELETE]
(
@ID INT
) AS

BEGIN
BEGIN TRY
BEGIN TRANSACTION TSALES

DELETE FROM PURCHASE_INVOICE_DETAILS WHERE PurchaseInvoiceID = @ID 

DELETE FROM PURCHASE_INVOICE WHERE ID= @ID

COMMIT TRANSACTION TSALES

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION TSALES
		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	RETURN -100
END CATCH
END
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_NAVIGATE_PURCHASE_INVOICE]
@PAGENO INT,
@ROWPERPAGE INT
AS
BEGIN

SELECT * FROM PURCHASE_INVOICE ORDER BY ID OFFSET (@PAGENO -1)*@ROWPERPAGE ROWS FETCH NEXT @ROWPERPAGE ROWS ONLY;
                    SELECT COUNT('X') FROM SALES_INVOICE;
END
GO



ALTER PROC [dbo].[SP_PURCHASE_INVOICE_ADD_EDIT]
(
@ID INT,
@VOUCHERNO NVARCHAR(30),
@DATE DATETIME,
@REMARKS NVARCHAR(200) = NULL,
@ENTITYNAME NVARCHAR(50) = '',
@TOTALBYACAMOUNT MONEY=0,
@NETAMOUNT MONEY=0,
@TOTALAMOUNT MONEY=0,
@GROSSAMOUNT MONEY=0,
@TOTALQTY FLOAT=0,
@SPECIALDISCOUNT MONEY=0,

@TOTALTCAMOUNT MONEY = 0,

@DETAILS XML, --TBLSALESINVOICEDETAIL READONLY,

@AUDITLOGCSV NVARCHAR(MAX) = NULL,
@IPADDRESS NVARCHAR(MAX) = NULL,
@MACADDRESS NVARCHAR(200) = NULL,
@COMPUTERNAME NVARCHAR(200) = NULL,

@COMPANYID INT =1,
@USERID NVARCHAR(20),   --IF ITEM ADDED THEN CREATED_BY ELSE MODIFIED BY
--@NETDISCOUNT DECIMAL(18,5) = NULL,
@RETURN NVARCHAR(20) OUTPUT
)
AS
BEGIN
BEGIN TRY
DECLARE @DOCHANDLE INT;
EXEC SP_XML_PREPAREDOCUMENT @DOCHANDLE OUTPUT, @DETAILS;

DECLARE @TBLDETAILS TABLE
	(
        PRODUCTID INT,
		PRODUCTCODE NVARCHAR(100),
        QUANTITY MONEY,
        PURCHASERATE MONEY,
        AMOUNT MONEY,
        DISCPERCENTAGE MONEY,
        DISCOUNTAMOUNT MONEY,
        NETAMOUNT MONEY,
        TAXAMOUNT MONEY,
        VAT MONEY,
        QTYUNITID INT,
        TAXID INT
	);

	-- INSERT INTO DETAILS TABLE
	INSERT INTO @TBLDETAILS(PRODUCTID,PRODUCTCODE,QUANTITY,PURCHASERATE,AMOUNT,DISCPERCENTAGE,
			DISCOUNTAMOUNT,NETAMOUNT,TAXAMOUNT,VAT,QTYUNITID,TAXID)
		SELECT PRODUCTID,PRODUCTCODE,QUANTITY,PRICE,AMOUNT,DISCPERCENT,DISCOUNT,NETAMOUNT,TAXAMOUNT,VATAMOUNT,
					QTYUNITID,TAXID
				FROM OPENXML( @DOCHANDLE, '/PURCHINVOICEDETAILS/DETAILS', 2)   WITH 
				(	PRODUCTID INT,
					PRODUCTCODE NVARCHAR(100),
					QUANTITY MONEY,
					PRICE MONEY,
					AMOUNT MONEY,
					DISCPERCENT MONEY,
					DISCOUNT MONEY,
					NETAMOUNT MONEY,
					TAXAMOUNT MONEY,
					VATAMOUNT MONEY,			
					QTYUNITID INT,
					TAXID INT) 

			--select * from @TBLDETAILS;
			--return;

	DECLARE @TTOTALGROSS MONEY, @TTOTALNET MONEY, @TTOTALDISC MONEY, @TTOTALQTY MONEY, @TTOTALTAX MONEY;

	SELECT @TTOTALGROSS = SUM(AMOUNT), @TTOTALNET= SUM(NETAMOUNT), @TTOTALDISC = SUM(DISCOUNTAMOUNT), @TTOTALTAX = SUM(TAXAMOUNT), @TTOTALQTY = SUM(QUANTITY) FROM @TBLDETAILS 

	--IF(@TTOTALGROSS <> @GROSSAMOUNT)
	--		RAISERROR('STATUS 400: GROSS AMOUNT CALCULATION IS NOT VALID!', 15,1);

	--IF(@TTOTALNET <> @NETAMOUNT)
	--		RAISERROR('STATUS 400: NET AMOUNT CALCULATION IS NOT VALID!', 15,1);

	--IF(@TTOTALQTY <> @TOTALQTY)
	--		RAISERROR('STATUS 400: TOTAL QUANTITY CALCULATION IS NOT VALID!', 15,1);

	--IF(@TTOTALDISC <> @SPECIALDISCOUNT)
	--		RAISERROR('STATUS 400: DISCOUNT AMOUNT CALCULATION IS NOT VALID!', 15,1);

	--IF(@TTOTALTAX <> @TOTALTCAMOUNT)
	--		RAISERROR('STATUS 400: TAX AMOUNT CALCULATION IS NOT VALID!', 15,1);

	--IF(@NETAMOUNT <>(@GROSSAMOUNT-@SPECIALDISCOUNT))
	--		RAISERROR('STATUS 400: NETAMOUNT MUST BE GROSSAMOUNT - SPECIALDISCOUNT!', 15,1);

	-- CHECK IF PRODUCTS EXIST IN GIVEN COMPANY
	IF EXISTS(SELECT * FROM @TBLDETAILS D WHERE PRODUCTID NOT IN(SELECT PRODUCTID FROM PRODUCT WHERE COMPANYID = @COMPANYID))
		RAISERROR('STATUS 400: PRODUCT(S) DONOT EXIST!', 15,1);

	DECLARE @RETURNVALUE INT =0;
	
	BEGIN TRANSACTION T
	IF(@ID<=0)
	BEGIN
			--REAL INSERT
		INSERT INTO PURCHASE_INVOICE(VOUCHERNO,[DATE],REMARKS,
			CREATED_BY,CREATED_DATE,NETAMOUNT,TOTALAMOUNT,GROSSAMOUNT,TOTALQTY,SPECIALDISCOUNT,TOTALBYACAMOUNT,
			TOTALTCAMOUNT,COMPANYID) 
			VALUES(
				@VOUCHERNO,@DATE,@REMARKS,
				@USERID,GETDATE(),@NETAMOUNT,@TOTALAMOUNT,@GROSSAMOUNT,@TOTALQTY,@SPECIALDISCOUNT,@TOTALBYACAMOUNT,
				@TOTALTCAMOUNT,@COMPANYID
			)

	SET @ID = SCOPE_IDENTITY();	
	SET @RETURN =@ID 

	END
	ELSE --MODIFY 
		BEGIN			
			-- CHECK IF ID EXISTS FOR COMPANYID
			IF NOT EXISTS(SELECT * FROM PURCHASE_INVOICE WHERE ID = @ID AND COMPANYID=@COMPANYID) 
				RAISERROR('STATUS 404: PURCHASE INVOICE DOES NOT EXIST!', 15,1);

			--REAL UPDATE
		UPDATE PURCHASE_INVOICE SET 
            VOUCHERNO=@VOUCHERNO ,
            [DATE] = @DATE,
			REMARKS=@REMARKS ,
			
			TOTALBYACAMOUNT =@TOTALBYACAMOUNT,
			NETAMOUNT=@NETAMOUNT,
			TOTALAMOUNT=@TOTALAMOUNT,
			TOTALQTY=@TOTALQTY,
			GROSSAMOUNT=@GROSSAMOUNT,
			SPECIALDISCOUNT=@SPECIALDISCOUNT,
			MODIFIED_BY=@USERID,
			MODIFIED_DATE=GETDATE(),
			ENTITYNAME= @ENTITYNAME,

			TOTALTCAMOUNT = @TOTALTCAMOUNT,
			COMPANYID = @COMPANYID
	WHERE ID = @ID 		
			SET @RETURN= @ID;

		DELETE FROM PURCHASE_INVOICE_DETAILS WHERE PURCHASEINVOICEID = @ID;
		
	END	

	INSERT INTO PURCHASE_INVOICE_DETAILS (PURCHASEINVOICEID,PRODUCTID,CODE,QUANTITY,PURCHASERATE,AMOUNT,DISCPERCENTAGE,
			DISCOUNT,NET_AMOUNT,TAXAMOUNT,VAT,QTYUNITID,TAXID)
		SELECT @ID, PRODUCTID,PRODUCTCODE,QUANTITY,PURCHASERATE,AMOUNT,DISCPERCENTAGE,
			DISCOUNTAMOUNT,NETAMOUNT,TAXAMOUNT,COALESCE(VAT,0.00),QTYUNITID,TAXID
		 FROM @TBLDETAILS


COMMIT TRANSACTION T
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION T
		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	SET @RETURN='FAILURE';
	RETURN -100
END CATCH
END

