
EXEC sp_rename 'dbo.Tax.TaxID', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.Tax.TaxCode', 'Code', 'COLUMN';
EXEC sp_rename 'dbo.Tax.TaxName', 'Name', 'COLUMN';
EXEC sp_rename 'dbo.Tax.Rate1', 'Rate', 'COLUMN';

go


ALTER      PROCEDURE [dbo].[SP_TAX_ADD_EDIT]
(
@ID INT,
@NAME NVARCHAR(150),
@CODE NVARCHAR(100),
@TAXPAIDACID INT = NULL,
@TAXRECACID INT = NULL,
@COMPANYID INT = 1,
@RATE DECIMAL(18,5),
@RATE2 DECIMAL(18,5) =0,
@REMARKS NVARCHAR(500)='',

@AUDITLOGCSV NVARCHAR(MAX) = NULL,
@IPADDRESS NVARCHAR(MAX) = NULL,
@MACADDRESS NVARCHAR(200) = NULL,
@COMPUTERNAME NVARCHAR(200) = NULL,

@USERID NVARCHAR(20) = 'ROOT',   --IF ITEM ADDED THEN CREATED_BY ELSE MODIFIED BY
@RETURN NVARCHAR(20)=0 OUTPUT
)
AS
BEGIN TRY
	--CHECK IF USER HAS PERMISSION
	DECLARE @AUTHORIZE NVARCHAR(20)
	IF(@ID<=0) SET @AUTHORIZE='TAX_SETUP_create or alter ' ELSE SET @AUTHORIZE = 'TAX_SETUP_MODIFY'
	

	--CHECK IF THE COMPANYID IS PROVIDED
	IF(@COMPANYID<=0)
		RAISERROR('STATUS 412: UNKNOWN COMPANY.', 15,1)
	
		-- CHECK FOR DUPLICATE ENTRY
	IF EXISTS (SELECT * FROM TAX WHERE CODE=@CODE AND ID<>@ID AND COMPANYID=@COMPANYID ) 
		RAISERROR('STATUS 409: DUPLICATE TAX CODE', 15,1)

	-- CHECK FOR DUPLICATE ENTRY
	IF EXISTS (SELECT * FROM TAX WHERE NAME=@NAME AND ID<>@ID AND COMPANYID=@COMPANYID ) 
		RAISERROR('STATUS 409: DUPLICATE TAX NAME', 15,1)
			

	IF (@ID<=0)  --ADD
		BEGIN
			--REAL INSERT
			INSERT INTO TAX(NAME, CODE, TAXPAIDACID, TAXRECACID, RATE, RATE2,REMARKS,CREATED_BY, CREATED_DATE,COMPANYID)
			VALUES(@NAME, @CODE, @TAXPAIDACID, @TAXRECACID, @RATE, @RATE2, @REMARKS, @USERID, GETDATE(), @COMPANYID)
			SET @RETURN= SCOPE_IDENTITY();
		END
	ELSE --MODIFY 
		BEGIN			
			-- CHECK IF ID EXISTS FOR COMPANYID
			IF NOT EXISTS(SELECT * FROM TAX WHERE ID=@ID AND COMPANYID=@COMPANYID) 
				RAISERROR('STATUS 404: TAX DOES NOT EXIST!', 15,1);

			--REAL UPDATE
			UPDATE TAX SET NAME = @NAME, CODE= @CODE, TAXRECACID= @TAXRECACID, TAXPAIDACID = @TAXPAIDACID, RATE= @RATE, RATE2 = @RATE2,
				 REMARKS = @REMARKS, MODIFIED_BY = @USERID, MODIFIED_DATE = GETDATE() WHERE ID = @ID;
			
			SET @RETURN= @ID;
		END

END TRY

BEGIN CATCH

		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	SET @RETURN='FAILURE';
	RETURN -100
END CATCH
go


ALTER PROCEDURE [DBO].[SP_TAX_DELETE]
(
@ID INT
) AS

BEGIN
BEGIN TRY

	IF EXISTS(SELECT 1 FROM SALES_INVOICE_DETAILS WHERE TAXID = @ID) 
		RAISERROR('STATUS 409: THIS TAX IS IN USE.', 15,1)

	IF	EXISTS(SELECT 1 FROM PURCHASE_INVOICE_DETAILS WHERE TAXID = @ID)
		RAISERROR('STATUS 409: THIS TAX IS IN USE.', 15,1)

	DELETE FROM TAX WHERE ID= @ID 

END TRY
BEGIN CATCH
		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	RETURN -100
END CATCH
END
GO

ALTER      PROCEDURE [dbo].[SP_GET_TAX]
@ID INT = 0
AS
BEGIN
	SELECT * FROM TAX WHERE ID = CASE WHEN @ID > 0 THEN @ID ELSE ID END

END
GO