EXEC sp_rename 'dbo.[UNIT].UnitMaintenanceID', 'ID', 'COLUMN';
EXEC sp_rename 'dbo.[UNIT].UNITNAME', 'NAME', 'COLUMN';

go

ALTER PROCEDURE [dbo].[SP_UNIT_ADD_EDIT](
@ID INT=0,
@NAME NVARCHAR(150),
@SYMBOL NVARCHAR(30),
@REMARKS NVARCHAR(150)='',

-- AUDIT LOG START
@AUDITLOGCSV NVARCHAR(MAX) = NULL,
@IPADDRESS NVARCHAR(MAX) = NULL,
@MACADDRESS NVARCHAR(200) = NULL,
@COMPUTERNAME NVARCHAR(200) = NULL,
-- AUDIT LOG END

@COMPANYID INT =1,
@USERID NVARCHAR(20),   --IF ITEM ADDED THEN CREATED_BY ELSE MODIFIED BY
@RETURN NVARCHAR(20) ='' OUTPUT
)
AS
BEGIN TRY
BEGIN TRANSACTION

	
	DECLARE @RETURNVALUE INT;

	-- CHECK FOR DUPLICATE ENTRY
	IF EXISTS (SELECT * FROM UNIT WHERE [NAME]=@NAME AND COMPANYID=@COMPANYID  AND ID<>@ID) 
		RAISERROR('STATUS 409: DUPLICATE UNIT NAME', 15,1)
	IF EXISTS (SELECT * FROM UNIT WHERE SYMBOL=@SYMBOL AND COMPANYID=@COMPANYID  AND ID<>@ID)
		RAISERROR('STATUS 409: DUPLICATE UNIT SYMBOL', 15,1)

	IF (@ID<=0)  --ADD 
		BEGIN					
			INSERT INTO UNIT([NAME], SYMBOL, REMARKS, COMPANYID, CREATED_BY, CREATED_DATE) 
			VALUES (@NAME, @SYMBOL, @REMARKS, @COMPANYID, @USERID, GETDATE());

			SET @RETURN = SCOPE_IDENTITY();

		END
	ELSE --MODIFY 
		BEGIN
			-- CHECK IF ID EXISTS FOR COMPANYID
			IF NOT EXISTS(SELECT * FROM UNIT WHERE ID=@ID AND COMPANYID=@COMPANYID) 
				RAISERROR('STATUS 404: UNIT DOES NOT EXIST!', 15,1);

			UPDATE UNIT SET [NAME]=@NAME, SYMBOL=@SYMBOL, REMARKS=@REMARKS, MODIFIED_BY=@USERID, MODIFIED_DATE=GETDATE() WHERE ID=@ID;

			SET @RETURN = @ID
		END


COMMIT TRANSACTION

END TRY

BEGIN CATCH
ROLLBACK TRANSACTION

	 DECLARE 
        @ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
        @ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
    RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	SET @RETURN='FAILURE';
	RETURN -100
END CATCH
go

ALTER PROCEDURE [dbo].[SP_UNIT_DELETE]
(
@ID INT
) AS

BEGIN
BEGIN TRY

	IF EXISTS(SELECT 1 FROM COMPOUND_UNIT WHERE UnitID = @ID or ParentUnitID = @ID)
		RAISERROR('STATUS 409: THIS UNIT HAS COMPOUND UNITS. PLEASE DELETE IT AND PROCEED.', 15,1)

	DELETE FROM UNIT WHERE ID= @ID 

END TRY
BEGIN CATCH
		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	RETURN -100
END CATCH
END
GO


ALTER PROCEDURE [dbo].[SP_GET_UNIT]
@ID INT = 0
AS
BEGIN
	SELECT * FROM UNIT WHERE ID = CASE WHEN @ID > 0 THEN @ID ELSE ID END

END
GO

ALTER PROCEDURE [dbo].[SP_GET_UNIT_CONVERSION_RATES]
(
    @BASEUNITID INT,
    @COMPANYID INT=0
)
AS
BEGIN
    SET NOCOUNT ON;

    
    -- TEMP WORK COPY OF YOUR TABLE
    
    DECLARE @UNITS TABLE (
        ID INT IDENTITY(1,1),
        UNITID INT,
        PARENTUNITID INT,
        RELATIONVALUE DECIMAL(18,5)
    );

    INSERT INTO @UNITS (UNITID, PARENTUNITID, RELATIONVALUE)
    SELECT 
        UNITID,
        PARENTUNITID,
        RELATIONVALUE
    FROM COMPOUND_UNIT

	--print 'here'
    
    -- RESULT TABLE
    
    DECLARE @RESULT TABLE (
        UNITID INT,
        CONVERSIONRATE DECIMAL(18,5)
    );

    -- INSERT THE BASE UNIT AS “1”
    INSERT INTO @RESULT VALUES (@BASEUNITID, 1);


    
    --  1. TRAVERSE UPWARD (PARENTS / ANCESTORS) 
    
    DECLARE 
        @CURR INT = @BASEUNITID,
        @PARENT INT,
        @RELATION DECIMAL(18,5) = 1,
        @ID INT;

    WHILE EXISTS (SELECT 1 FROM @UNITS WHERE UNITID = @CURR)
    BEGIN
        SELECT TOP 1
            @ID = ID,
            @PARENT = PARENTUNITID,
            @RELATION = @RELATION * RELATIONVALUE
        FROM @UNITS
        WHERE UNITID = @CURR;

        IF @PARENT IS NOT NULL
            INSERT INTO @RESULT VALUES (@PARENT, @RELATION);

        DELETE FROM @UNITS WHERE ID = @ID;

        SET @CURR = @PARENT;
    END;


    --  2. TRAVERSE DOWNWARD (CHILDREN / DESCENDANTS) 

    SET @CURR = @BASEUNITID;
    SET @RELATION = 1;

    WHILE EXISTS (SELECT 1 FROM @UNITS WHERE PARENTUNITID = @CURR)
    BEGIN
        SELECT TOP 1
            @ID = ID,
            @CURR = UNITID,
            @RELATION = @RELATION / RELATIONVALUE
        FROM @UNITS
        WHERE PARENTUNITID = @CURR;

        INSERT INTO @RESULT VALUES (@CURR, @RELATION);

        DELETE FROM @UNITS WHERE ID = @ID;
    END;


    -- FINAL OUTPUT WITH UNIT NAMES
    SELECT
        R.UNITID ID,
        UM.[NAME],
		@BASEUNITID DEFAULTUNITID,
        R.CONVERSIONRATE
    FROM @RESULT R
    LEFT JOIN UNIT UM
        ON UM.ID = R.UNITID
    ORDER BY R.CONVERSIONRATE DESC;
END

GO