EXEC sp_rename 'dbo.[User].UserID', 'ID', 'COLUMN';
go

CREATE OR ALTER PROCEDURE [dbo].[SP_GET_USER]
@ID INT = 0,
@USERNAME NVARCHAR(50) = ''
AS
BEGIN
	SELECT ID, USERNAME, NAME, ADDRESS, CONTACT [PHONENO], EMAIL,DEPARTMENT, [PASSWORD], [ROLE] FROM [USER] 
	WHERE ID = CASE WHEN @ID > 0 THEN @ID ELSE ID END
	AND USERNAME = CASE WHEN @USERNAME != '' THEN @USERNAME ELSE USERNAME END

END
GO


CREATE OR ALTER PROCEDURE [dbo].[SP_GET_PASSWORD_BY_USERID]
@ID INT
AS
BEGIN
 SELECT PASSWORD FROM [USER] WHERE ID = @ID
END
GO

ALTER      PROCEDURE [dbo].[SP_PASSWORD_UPDATE]
@ID INT,
--@OLDPASSWORD VARCHAR(200),
@NEWPASSWORD VARCHAR(200)
AS

UPDATE [USER] SET [PASSWORD] = @NEWPASSWORD WHERE ID = @ID

GO

ALTER PROCEDURE [dbo].[SP_USER_DELETE]
(
@ID INT
) AS

BEGIN
BEGIN TRY

	IF EXISTS(SELECT 1 FROM [USER] WHERE ID = @ID AND ISBUILTIN = 1) 
		RAISERROR('STATUS 409: CANNOT DELETE BUILT-IN USER.', 15,1)

	-- just set the userstatus to inactive for now before deleting
	UPDATE [USER] SET USERSTATUS = 0 WHERE [ID] = @ID

END TRY
BEGIN CATCH
		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	RETURN -100
END CATCH
END
GO


ALTER        PROCEDURE [dbo].[SP_USER_ADD_EDIT]
(
@ID INT,
@USERNAME NVARCHAR(150),
@PASSWORD NVARCHAR(300)=NULL,
@NAME NVARCHAR(150),
@ADDRESS NVARCHAR(100),
@PHONENO NVARCHAR(20),
@EMAIL NVARCHAR(30)=NULL,
@DEPARTMENT NVARCHAR(30)='',
@USERSTATUS BIT = 1,

@AUDITLOGCSV NVARCHAR(MAX) = NULL,
@IPADDRESS NVARCHAR(MAX) = NULL,
@MACADDRESS NVARCHAR(200) = NULL,
@COMPUTERNAME NVARCHAR(200) = NULL,

@COMPANYID INT=1,
@REMARKS NVARCHAR(500)='',
@USERID NVARCHAR(20)='ROOT',   --IF ITEM ADDED THEN CREATED_BY ELSE MODIFIED BY
@RETURN NVARCHAR(20)  =0 OUTPUT
)
AS
BEGIN TRY
BEGIN TRANSACTION T

	--CHECK IF USER HAS PERMISSION
	--DECLARE @AUTHORIZE NVARCHAR(20)
	--IF(@ID<=0) SET @AUTHORIZE='USER_create or alter ' ELSE SET @AUTHORIZE = 'USER_MODIFY'
	--IF FNCHECKACCESS(@AUTHORIZE, @USERID, @COMPANYID)=0
	--	RAISERROR('STATUS 401: NOT AUTHORIZED TO PERFORM THIS ACTION', 15,1)

	--CHECK IF THE COMPANYID IS PROVIDED
	IF(@COMPANYID<=0)
		RAISERROR('STATUS 412: UNKNOWN COMPANY.', 15,1)
	
	-- CHECK FOR DUPLICATE ENTRY
	IF EXISTS (SELECT * FROM [USER] WHERE USERNAME=@USERNAME AND ID<>@ID)-- AND COMPANYID=@COMPANYID ) 
		RAISERROR('STATUS 409: DUPLICATE USERNAME. USERNAME ALREADY EXISTS FOR SAME/ OTHER COMPANY !', 15,1)
		
	
   
    DECLARE @RETURNVALUE INT =0;

	IF (@ID<=0)  --ADD
		BEGIN
			--REAL INSERT
			INSERT INTO [USER](USERNAME, PASSWORD, NAME, ADDRESS, CONTACT, EMAIL, DEPARTMENT, CREATEDBY, CREATEDDATE, COMPANYID, USERSTATUS)
				VALUES(@USERNAME, @PASSWORD, @NAME, @ADDRESS, @PHONENO, @EMAIL, @DEPARTMENT, @USERID, GETDATE(), @COMPANYID, @USERSTATUS)

			SET @RETURN = SCOPE_IDENTITY();

		

		END
	ELSE --MODIFY 
		BEGIN			
			-- CHECK IF ID EXISTS FOR COMPANYID
			IF NOT EXISTS(SELECT * FROM [USER] WHERE ID=@ID AND COMPANYID=@COMPANYID) 
				RAISERROR('STATUS 404: USER DOES NOT EXIST!', 15,1);


			-- IF PASSWORD IS NULL, THEN DONOT UPDATE PASSWORD
			IF(@PASSWORD IS NULL OR @PASSWORD = '')
				UPDATE [USER] SET NAME = @NAME, ADDRESS= @ADDRESS, EMAIL = @EMAIL, DEPARTMENT = @DEPARTMENT, 
				CONTACT = @PHONENO, MODIFIEDBY = @USERID, MODIFIEDDATE = GETDATE()
				 WHERE ID = @ID;

			--ELSE 
			--REAL UPDATE
			ELSE
				UPDATE [USER] SET NAME = @NAME, ADDRESS= @ADDRESS, EMAIL = @EMAIL, DEPARTMENT = @DEPARTMENT 
				-- ,PASSWORD = @PASSWORD -- DONOT UPDATE PASSWORD 
					,CONTACT = @PHONENO,  MODIFIEDBY = @USERID,MODIFIEDDATE = GETDATE()
				 WHERE ID = @ID;

			set @RETURN = @ID;
		END

COMMIT TRANSACTION T
RETURN @RETURNVALUE;
END TRY

BEGIN CATCH
		ROLLBACK TRANSACTION T

		DECLARE 
		@ERRORMESSAGE NVARCHAR(MAX), @ERRORSEVERITY INT, @ERRORSTATE INT;
	SELECT 
		@ERRORMESSAGE = ERROR_MESSAGE(), @ERRORSEVERITY = ERROR_SEVERITY(), @ERRORSTATE = ERROR_STATE();
	RAISERROR (@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE);
	SET @RETURN='FAILURE';
	RETURN -100
END CATCH
GO